version: '3.1'
services:
  db:
    image: mysql:5.7.37
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: coderslab
      MYSQL_DATABASE: bookStore
    ports:
      - "3306:3306"
    volumes:
      - /Users/koszkuld/projects/private/hibernate/volumes/mysql:/var/lib/mysql